### ISSUE TITLE
Would you like to see this feature implemented?

### ISSUE THREAD

**Issue by grtcdr** [grtcdr/macchina#10]
Macchina, in its current state, prints basic system information.
Would you like to see me implement _different pages_ containing _different information_, for example:
- A page containing all **power** (display, battery) related information.
- A page containing all **usage** (memory, swap) related information.

![image](https://user-images.githubusercontent.com/35816711/107836610-1042b680-6d9e-11eb-8a6f-674ceabba65f.png)

**Comment by luccahuguet** [comment]
Cool!
