### ISSUE TITLE
Don't report a DE if WM is detected

### ISSUE THREAD

**Issue by federicotorrielli** [grtcdr/macchina#13]
If a WM is detected, it's useless to have the same String on DE, because you can't logically have a WM and a DE both running ofc.
![image](https://user-images.githubusercontent.com/31370059/109413960-86573800-79b0-11eb-9fa2-b9b863d41eb4.png)

**Comment by grtcdr** [comment]
Thanks for reporting that, totally missed it.
I'll make sure to take that into account in the next update!

**Comment by grtcdr** [comment]
https://github.com/grtcdr/macchina/commit/ee036267dc0e2e5be15fe6be1829d00af581a411 should fix this issue.

**Comment by federicotorrielli** [comment]
In the update herbstluftwm shows because you are checking for the same exact string, can you check for the string but without capitalization?

Like: herbstluftwm == Herbstluftwm

**Comment by grtcdr** [comment]
Yeah I'll do that, I didn't notice that from the picture.
