### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by creepinson** [grtcdr/macchina#16]
As it says on the readme - macos support isn't currently implemented. I also get this when building this package via cargo:

```
error[E0425]: cannot find function `percentage` in module `battery`
 --> /Users/theoparis/.cargo/registry/src/github.com-1ecc6299db9ec823/macchina-0.5.4/src/bars.rs:7:20
  |
7 |     match battery::percentage(fail)
  |                    ^^^^^^^^^^ not found in `battery`
```
and a ton of other very similar errors.

**Comment by 123marvin123** [comment]
I'm currently working on a macOS port and maybe a windows port if I find some more time.

**Comment by grtcdr** [comment]
This is happening because a lot of functions are **conditionally compiled**.
For example, (battery) percentage, (battery) status and a ton of other functions have a **cfg** attribute `#[cfg(target_os = "osname")]` that only compiles that part of the source code if your **OS** matches the value of the attribute that was set for it.

```
#[cfg(target_os = "linux")]
pub fn percentage(fail: &mut Fail) -> String {
...
}
```

Only two platforms are supported at the moment, and the functions that fetch the information are conditionally compiled, so that's why you're receiving these errors.

**Comment by 123marvin123** [comment]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/7266447/110695720-7d553a80-81ea-11eb-9930-94f4c8760ca0.png">

<img width="774" alt="image" src="https://user-images.githubusercontent.com/7266447/110695814-9bbb3600-81ea-11eb-8c96-6990d623589a.png">

Hooking directly into sysctl and core-foundation offers extremely high speeds (0.1ms +- 0.1ms vs 481ms neofetch)

**Comment by 123marvin123** [comment]
> > <img alt="image" width="534" src="https://user-images.githubusercontent.com/7266447/110695720-7d553a80-81ea-11eb-9930-94f4c8760ca0.png">
> > <img alt="image" width="774" src="https://user-images.githubusercontent.com/7266447/110695814-9bbb3600-81ea-11eb-8c96-6990d623589a.png">
> > Hooking directly into sysctl and core-foundation offers extremely high speeds (0.1ms +- 0.1ms vs 481ms neofetch)
> 
> Awesome, absolutely terrific work!
> 4000 times faster than Neofetch is an astonishing number 😀
> 
> EDIT: Are you sure macchina is in your PATH?
> I noticed at first you used `./macchina` to run macchina and then used `macchina` when benchmarking.
> Using the -i argument will ignore failures, and if Macchina isn't in your `PATH` you'll get a very quick execution time because the command failed.
> Only saying this because 0.1 ms is very low compared to the amount of code that is run when `macchina` is executed.

You are right, I didn't know that the benchmarking tool needs the be able to access the application via the path variable. I made a new benchmark, the result is still very good:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/7266447/110701713-cfe62500-81f1-11eb-8e07-e55afc4a93b0.png">

**Comment by grtcdr** [comment]
@123marvin123 
Yeah I didn't know it either at first, but after using it a little too many times I noticed how it only picks up on only the programs that are in your PATH, aliases don't work either.

Anyways, the execution time is still really amazing, faster than my implementation for Linux.

**Comment by 123marvin123** [comment]
> @123marvin123
> Yeah I didn't know it either at first, but after using it a little too many times I noticed how it only picks up on only the programs that are in your PATH, aliases don't work either.
> 
> Anyways, the execution time is still really amazing, faster than my implementation for Linux.

We can optimize the linux implementation by not spawning new processes for retrieving os information. Instead, we can use sysctl c api (wrapped in a nice rust api) and other native functionality. We should be able to get similar performance on Linux and NetBSD this way.

**Comment by grtcdr** [comment]
I didn't know this API existed, and you're right, spawning a process for everything slows the program down.
I'll start converting all functions whose value can be retrieved through sysctl to use the sysctl API.

**Comment by grtcdr** [comment]
@creepinson, Support for macOS should be out very soon.
@123marvin123 has done an excellent job at this, as well as rewriting a huge portion of the codebase.
We're working on documentation right now to enhance code readability, but it shouldn't take too long :smile:

**Comment by grtcdr** [comment]
@creepinson, support for macOS has now been merged into `main` :partying_face:
