### ISSUE TITLE
extra::which should use directories from PATH

### ISSUE THREAD

**Issue by 123marvin123** [grtcdr/macchina#17]
The `extra::which` function, which checks if a program exists, should search in all folder that are given in the PATH variable.

https://github.com/grtcdr/macchina/blob/74f5e9acd097a11c3065e3902d81fd747aa17664/src/extra.rs#L40-L56

**Comment by grtcdr** [comment]
Yeah, I agree.
Will do!

**Comment by grtcdr** [comment]
https://github.com/grtcdr/macchina/commit/c8cae0fb3e1cb6c722d5083ded7cc195062699d2 addresses this problem.
`extra::which` is now able to look through all directories listed in `PATH`, avoiding the hardcoded path mess.
