### ISSUE TITLE
Add an AUR package.

### ISSUE THREAD

**Issue by dessalines** [grtcdr/macchina#2]
Not necessarily for you to do, but someone who's familiar with creating AUR packages from rust binaries could do this very easily.

**Comment by grtcdr** [comment]
I've **always** wanted to learn how to do this, I'll add it to my to-do list and I'll post the link in the README once everything is good to go!

**Comment by grtcdr** [comment]
I couldn't figure out how to add an AUR package, but in the meantime, macchina is available on [crates.io](https://crates.io/crates/macchina)
I'm not giving up though, it will be available in the AUR!

**Comment by grtcdr** [comment]
Update: the PKGBUILD is good to go, I'll upload it as soon as I can.

**Comment by grtcdr** [comment]
Macchina is now available on the [AUR](https://aur.archlinux.org/packages/macchina/)
