### ISSUE TITLE
[BUG] Macchina crashes on --theme def

### ISSUE THREAD

**Issue by uttarayan21** [grtcdr/macchina#20]
**Describe the bug**
Using 
```bash
macchina -t def
```
causes 
```
memory allocation of 18446744073709551613 bytes failed
[1]    22666 abort (core dumped)  macchina -t def
```

**To Reproduce**
1.  macchina -t def

**Expected behavior**
Run normally

**Screenshots**
![macchina bug](https://user-images.githubusercontent.com/18732700/110763286-b8517f80-8277-11eb-9363-ebbe1e77e3d6.png)

**System Information**
 - Distribution: Arch Linux
 - Desktop Environment: bspwm 
 - Terminal: Alacritty 0.7.2-1
 - Macchina's version: v0.5.5

**Additional context**

**Comment by 123marvin123** [comment]
@grtcdr Crash occurs in https://github.com/grtcdr/macchina/blob/7fe9d7e390cb664cb050c7b7b52a10b29646b29b/src/display.rs#L367 function, because `longest_key.len()` < `current_key.len()` which causes the `usize` to go into the negative (overflow).

**Comment by grtcdr** [comment]
The sanest solution I think is to remove the `def` theme, because it's the default theme, it is no different from running `macchina` without the `--theme` argument.

**Comment by grtcdr** [comment]
I removed `def` from the theme list in the latest commit https://github.com/grtcdr/macchina/commit/ebde6b48c03bacebe453b8f1ef79d4f07345ef3f and released a new version [v0.5.6](https://crates.io/crates/macchina)

**Comment by uttarayan21** [comment]
Thanks for fixing.

**Comment by grtcdr** [comment]
Of course! and thank you for reporting it :smile:
