### ISSUE TITLE
[BUG] Macchina doesn't report battery stats

### ISSUE THREAD

**Issue by uttarayan21** [grtcdr/macchina#21]
**Describe the bug**
machina doesn't report battery status from laptop
It seems that macchina reads battery stats from hardcoded `/sys/class/power_supply/BAT0/` folder
But In my system the battery is in `/sys/class/power_supply/BAT1/` folder.
The `acpi` command seems to correctly report the battery status in my system. 

**To Reproduce**
1. machina --debug

**Expected behavior**
macchina reports battery stats

**Screenshots**
![macchina_batter](https://user-images.githubusercontent.com/18732700/110763739-36ae2180-8278-11eb-85fc-6eeeec7ec4fd.png)

**System Information**
 - Distribution: Arch Linux
 - Desktop Environment: bspwm
 - Terminal: Alacritty 0.7.2-1
 - Macchina's version: v0.5.5
**Additional context**

**Comment by grtcdr** [comment]
https://github.com/grtcdr/macchina/commit/ebde6b48c03bacebe453b8f1ef79d4f07345ef3f (v0.5.6) now includes a fallback path to read battery information from.

**Comment by uttarayan21** [comment]
Thanks for fixing the issue.
I didn't consider the runtime cost for calling awk.

**Comment by grtcdr** [comment]
It's all good, at some point in Macchina's development, **awk** and **sed** were being utilized to fetch system information.
And then I learned about hyperfine and bechmarking programs, and discovered that Macchina was so slow, it defeated its own purpose, that is performance.
I quickly rewrote most functions and stopped using awk and sed after that.
