### ISSUE TITLE
[BUG] shell output starts with hyphen in some rare cases

### ISSUE THREAD

**Issue by grtcdr** [grtcdr/macchina#25]
## Reporting an issue that a user raised
I'm not sure if this bug still persists as it was raised before the newer shell implementation that was recently merged into `main`.

**Describe the bug**
Most of the time, `shell` output is printed just fine. But in some rare cases, `shell` output can begin with a hyphen, e.g.
` Shell    — -zsh`

**To Reproduce**
1. Run `macchina`
2. Observe terminal value

**Expected behavior**
Shell value should never start with a hyphen.

**Screenshots**
No screenshot provided

**System Information**
 - Distribution: __N/A__
 - Desktop Environment: __N/A__
 - Terminal: __Tmux: server__
 - Macchina's version: __N/A__ (=0.5.4?)

**Comment by uttarayan21** [comment]
Htop outputs of the shells in bare terminal vs in tmux 
![normal shell](https://user-images.githubusercontent.com/18732700/111027225-de605680-8414-11eb-97af-1b244bba43c8.png)
![tmux shell](https://user-images.githubusercontent.com/18732700/111027230-ef10cc80-8414-11eb-81fc-935fe0d9102b.png)

Best way would probably be reading the $SHELL environment variable which is what neofetch seems to do, so it should be compatible with most systems.

**Comment by 123marvin123** [comment]
What version are you using? I a more recent version of Macchina, I changed how the shell will be read by using the "getpwuid()" function which should return the full path to the shell executable. Works fine on macOS:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/7266447/111027404-6a13bc00-83f0-11eb-88a1-02bf75b587be.png">

**Comment by grtcdr** [comment]
@uttarayan21 So this only affects tmux sessions?

**Comment by uttarayan21** [comment]
Oh didn't realise there was an update.I was using v0.5.7, now v0.5.9 works fine.
![screenshot](https://user-images.githubusercontent.com/18732700/111028033-f1c1f080-8419-11eb-9f90-eb9362954754.png)

@grtcdr As far as I can tell it only affected tmux sessions.

**Comment by grtcdr** [comment]
Awesome, thanks @123marvin123 for the new implementation :)
