### ISSUE TITLE
Add macOS benchmarks to README files

### ISSUE THREAD

**Issue by grtcdr** [grtcdr/macchina#28]
# Benchmarks

In order to showcase _Macchina's_ performance across the different platforms it supports, we need to add a macOS specific benchmark, in comparison to _Neofetch_ under the "Benchmarks" section of both`README.md` and `README_CARGO.md`

**Comment by 123marvin123** [comment]
That's a good idea, but I think the linux version still contains some code that is not as fast as it could be. For example, there are a still two occurrences of spawning a "sysctl" process, even though we could use the c library:

https://github.com/grtcdr/macchina/blob/935b6ece905103cf0227ce3dbd7dcbb3f540eea1/macchina-read/src/linux/mod.rs#L50

I will create a PR. I also have one other thing regarding performance that I want to try out before we publish benchmark results.

**Comment by grtcdr** [comment]
Yeah, I've noticed that too, but I didn't get around to rewriting them, I'll wait for your PR.
