### ISSUE TITLE
[BUG] `wmctrl` displays an error when running from `ssh`

### ISSUE THREAD

**Issue by laurentlbm** [grtcdr/macchina#42]
**Describe the bug**
When running `macchina` in `ssh` (or `et`), the error `Cannot open display` is shown multiple times and the `WM` data row is still displayed.

**To Reproduce**
1. Connect to your machine through `ssh`.
2. Run `macchina`.

**Expected behavior**
No error displayed and `WM -` row hidden.

**Screenshots**
![Screenshot_20210316-135745_Termux](https://user-images.githubusercontent.com/1180863/111357659-e3651600-865f-11eb-9288-c1675ff93e85.png)

**System Information**
 - Distribution: Arch Linux, Fedora
 - Desktop Environment: None
 - Terminal: ssh
 - Macchina's version: v0.5.9

**Comment by grtcdr** [comment]
Thanks for reporting this!

I'll check this out ASAP :+1:

**Comment by grtcdr** [comment]
https://github.com/grtcdr/macchina/commit/2c769066dcaab67d14bc4de1157c4b01d27483f1 should fix this :smile:

**Comment by laurentlbm** [comment]
Works great, thanks!

**Comment by grtcdr** [comment]
I'm gonna try and eliminate duplicate words in machine information, keep an eye out on the repo if you can :+1:
