### ISSUE TITLE
Make clippy happy

### ISSUE THREAD

**Issue by uttarayan21** [grtcdr/macchina#54]
**Enhancement**
Cargo [clippy](https://github.com/rust-lang/rust-clippy) reports a lot of warnings.
```bash
error: aborting due to 3 previous errors; 41 warnings emitted
error: could not compile `macchina`
```
**To Reproduce**
- Clone
-  run `cargo clippy`

This could be fixed to improve code quality and avoid errors.

**Comment by uttarayan21** [comment]
Okay it seems that I forgot to `git pull` so the older version had a lot more issues.
The latest clone seems to have a lot less warnings (like 6 warnings).

**Comment by 123marvin123** [comment]
> Okay it seems that I forgot to `git pull` so the older version had a lot more issues.
> The latest clone seems to have a lot less warnings (like 6 warnings).

Hi, I was about to ask you on which OS you are running and how you are invoking clippy. Because on my system (and also the GitHub Actions) I only see 5 warnings. But I guess the problem has solved itself :)
