### ISSUE TITLE
[BUG] incorrect terminal info on macOS

### ISSUE THREAD

**Issue by grtcdr** [grtcdr/macchina#57]
**Describe the bug**
Macchina on macOS reports "Login" as terminal, because of a possibly wrong argument being used to fetch the terminal in `shared::terminal()`

**To Reproduce**
1. run `macchina`
2. inspect terminal element

**Expected behavior**
Terminal should print the running terminal's name.

**System Information**
 - Operating System: macOS
 - Macchina's version: 0.6.1

**Comment by 123marvin123** [comment]
Happens on macOS too

**Comment by grtcdr** [comment]
Closing as your PR (#61) addresses this issue.
