### ISSUE TITLE
Unefficient way to count pkgs

### ISSUE THREAD

**Issue by federicotorrielli** [grtcdr/macchina#8]
Title.
IMO using rust to count output lines it's less efficient than having the count done with `pacman -Qq | wc -l`. I've done a test with hyperfine only taking the chunk of code that counts packages and comparing it with that line and ofc the shell command is faster.
Just letting you know, great job btw!
(Also, remember to update the AUR pkg on the releases :D)

EDIT: I have found an alternative implementation, maybe you can import it and use it; https://github.com/alex/line-counter/blob/master/src/main.rs

**Comment by grtcdr** [comment]
The previous implementation spawned `pacman -Qq` and piped its output to `wc -l`, and I thought that spawning two commands would be slower than the current implementation, I'll take a look at it again.

**Comment by grtcdr** [comment]
You're right, `pacman -Qq | wc -l` is in fact faster than the current implementation, I'll roll out the updates ASAP.
